package com.bank.bian.securitiespositionkeeping;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Securities Position Keeping
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Securities
 * Functional Pattern: Maintain
 * Asset Type:         Securities Position
 * Control Record:     Securities Position Maintenance Agreement
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Securities Position Keeping — BIAN Semantic API")
                .description("Service Domain 'Securities Position Keeping' (Maintain pattern) "
                        + "operating on the 'Securities Position Maintenance Agreement' control record.")
                .version("0.1.0"));
    }
}
